export type AnimeType = Partial<{
    id:                         number;
    airingSchedule:             string // should change;
    averageScore:               number;
    bannerImage:                string;
    chapters:                   number;
    characters:                 string // should change;
    countryOfOrigin:            string // should change;
    coverImage: Partial<{
        color:                  string;
        extraLarge:             string;
        large:                  string;
        medium:                 string;
    }>;
    description:                string;
    duration:                   number;
    endDate:                    string // should change;
    episodes:                   number;
    externalLinks:              string // should change;
    favourites:                 number;
    format:                     string // should change;
    genres:                     Array<string>;
    hashtag:                    string;
    idMal:                      number;
    isAdult:                    boolean;
    isFavourite:                boolean;
    isFavouriteBlocked:         boolean;
    isLicensed:                 boolean;
    isLocked:                   boolean;
    isRecommendationBlocked:    boolean;
    isReviewBlocked:            boolean;
    meanScore:                  number;
    mediaListEntry:             string // should change;
    modNotes:                   string;
    nextAiringEpisode:          string // should change;
    popularity:                 number;
    rankings:                   string // should change;
    recommendations:            string // should change;
    relations:                  string // should change;
    reviews:                    string // should change;
    season:                     string // should change;
    seasonInt:                  number;
    seasonYear:                 number;
    siteUrl:                    string;
    source:                     string // should change;
    staff:                      string // should change;
    startDate:                  string // should change;
    stats:                      string // should change;
    status:                     string // should change;
    streamingEpisodes:          string // should change;
    studios:                    string // should change;
    synonyms:                   string // should change;
    tags:                       string // should change;
    title: Partial<{
        english:                string;
        native:                 string;
        romaji:                 string;
        userPreferred:          string;
    }>;
    trailer:                    string // should change;
    trending:                   number;
    trends:                     string // should change;
    type:                       string // should change;
    updatedAt:                  number;
    volumes:                    number;
}>;