export type QueryType =
    | "averageScore"
    | "bannerImage"
    | "chapters"

    | "characters.nodes.age"
    | "characters.nodes.description"
    | "characters.nodes.favourites"
    | "characters.nodes.gender"
    | "characters.nodes.id"
    | "characters.nodes.image"
    | "characters.nodes.isFavourite"
    | "characters.nodes.isFavouriteBlocked"
    | "characters.nodes.name"
    | "characters.nodes.siteUrl"

    | "countryOfOrigin"

    | "coverImage.color"
    | "coverImage.extraLarge"
    | "coverImage.large"
    | "coverImage.medium"

    | "description"
    | "duration"

    | "endDate.day"
    | "endDate.month"
    | "endDate.year"

    | "episodes"

    | "externalLinks.color"
    | "externalLinks.icon"
    | "externalLinks.id"
    | "externalLinks.isDisabled"
    | "externalLinks.language"
    | "externalLinks.notes"
    | "externalLinks.site"
    | "externalLinks.siteId"
    | "externalLinks.type"
    | "externalLinks.url"

    | "favourites"
    | "format"
    | "genres"
    | "hashtag"
    | "id"
    | "idMal"
    | "isAdult"
    | "isFavourite"
    | "isFavouriteBlocked"
    | "isLicensed"
    | "isLocked"
    | "isRecommendationBlocked"
    | "isReviewBlocked"
    | "meanScore"
    | "modNotes"

    | "nextAiringEpisode.airingAt"
    | "nextAiringEpisode.episode"
    | "nextAiringEpisode.id"
    | "nextAiringEpisode.timeUntilAiring"

    | "popularity"

    | "rankings.allTime"
    | "rankings.context"
    | "rankings.format"
    | "rankings.id"
    | "rankings.rank"
    | "rankings.season"
    | "rankings.type"
    | "rankings.year"

    | "relations.nodes.title.english"
    | "relations.nodes.title.native"
    | "relations.nodes.title.romaji"
    | "relations.nodes.title.userPreferred"

    | "reviews.nodes.body"
    | "reviews.nodes.createdAt"
    | "reviews.nodes.id"
    | "reviews.nodes.private"
    | "reviews.nodes.rating"
    | "reviews.nodes.ratingAmount"
    | "reviews.nodes.score"
    | "reviews.nodes.siteUrl"
    | "reviews.nodes.summary"
    | "reviews.nodes.updatedAt"
    | "reviews.nodes.user.avatar.large"
    | "reviews.nodes.user.avatar.medium"
    | "reviews.nodes.user.name"
    | "reviews.nodes.userId"
    | "reviews.nodes.userRating"

    | "season"
    | "seasonInt"
    | "seasonYear"
    | "siteUrl"
    | "source"

    | "startDate.day"
    | "startDate.month"
    | "startDate.year"

    | "stats.scoreDistribution.amount"
    | "stats.scoreDistribution.score"
    | "stats.statusDistribution.amount"
    | "stats.statusDistribution.status"

    | "status"

    | "streamingEpisodes.site"
    | "streamingEpisodes.thumbnail"
    | "streamingEpisodes.title"
    | "streamingEpisodes.url"

    | "studios.nodes.favourites"
    | "studios.nodes.id"
    | "studios.nodes.isAnimationStudio"
    | "studios.nodes.isFavourite"
    | "studios.nodes.name"
    | "studios.nodes.siteUrl"

    | "synonyms"

    | "tags.category"
    | "tags.description"
    | "tags.id"
    | "tags.isAdult"
    | "tags.isGeneralSpoiler"
    | "tags.isMediaSpoiler"
    | "tags.name"
    | "tags.rank"
    | "tags.userId"

    | "title.english"
    | "title.native"
    | "title.romaji"
    | "title.userPreferred"

    | "trailer.id"
    | "trailer.site"
    | "trailer.thumbnail"

    | "trending"

    | "trends.averageScore"
    | "trends.date"
    | "trends.episode"
    | "trends.inProgress"
    | "trends.popularity"
    | "trends.releasing"
    | "trends.trending"

    | "type"
    | "updatedAt"
    | "volumes";