import { SeasonType } from "@/types/Anime/Queries/Season.type";
import { FormatType } from "@/types/Anime/Queries/Format.type";
import { StatusType } from "@/types/Anime/Queries/Status.type";
import { SortType } from "@/types/Anime/Queries/Sort.type";
import { SourceType } from "@/types/Anime/Queries/Source.type";

export type VariablesType = Partial<{
    type:                 "ANIME" | "MANGA";
    id:                   number;
    idMal:                number;
    season:               SeasonType;
    seasonYear:           number;
    format:               FormatType;
    status:               StatusType;
    sort:                 SortType;
    episodes:             number;
    duration:             number;
    isAdult:              boolean;
    genre:                string;
    genre_in:             Array<string>;
    tag_in:               Array<string>;
    tag:                  string;
    onList:               boolean;
    licensedBy:           string;
    licensedById:         number;
    averageScore:         number;
    averageScore_greater: number;
    popularity:           number;
    search:               string;
    source:               SourceType;
    startDate_greater:    number;
    endDate_lesser:       number;
    episodes_greater:     number;
    episodes_lesser:      number;
    duration_greater:     number;
    duration_lesser:      number;
    // MediaList
    userName:             string;
    mediaListStatus:      "COMPLETED" | "CURRENT" | "DROPPED" | "PAUSED" | "PLANNING" | "REPEATING";
}>;
