export const ParameterType = {
    Int:         "Int",
    String:      "String",
    Boolean:     "Boolean",
    MediaSeason: "MediaSeason",
    MediaType:   "MediaType",
    MediaFormat: "MediaFormat",
    MediaStatus: "MediaStatus",
    MediaSort:   "[MediaSort]",
};
export const QueryParametersType = {
    id:           ParameterType.Int,
    idMal:        ParameterType.Int,
    season:       ParameterType.MediaSeason,
    seasonYear:   ParameterType.Int,
    type:         ParameterType.MediaType,
    format:       ParameterType.MediaFormat,
    status:       ParameterType.MediaStatus,
    episodes:     ParameterType.Int,
    duration:     ParameterType.Int,
    isAdult:      ParameterType.Boolean,
    genre:        ParameterType.String,
    tag:          ParameterType.String,
    onList:       ParameterType.Boolean,
    licensedBy:   ParameterType.String,
    licensedById: ParameterType.Int,
    averageScore: ParameterType.Int,
    popularity:   ParameterType.Int,
    search:       ParameterType.String,
    sort:         ParameterType.MediaSort,
};