import {StatusType} from "@/types/Shikimori/StatusType";
import {IncompleteDateType} from "@/types/Shikimori/IncompleteDateType";
import {PosterType} from "@/types/Shikimori/PosterType";
import {GenreType} from "@/types/Shikimori/GenreType";
import {StudioType} from "@/types/Shikimori/StudioType";
import {ExternalLinkType} from "@/types/Shikimori/ExternalLinkType";
import {PersonRoleType} from "@/types/Shikimori/PersonRoleType";
import {CharacterRoleType} from "@/types/Shikimori/CharacterRoleType";
import {RelatedType} from "@/types/Shikimori/RelatedType";
import {VideoType} from "@/types/Shikimori/VideoType";
import {ScreenshotType} from "@/types/Shikimori/ScreenshotType";
import {ScoreStatType} from "@/types/Shikimori/ScoreStatType";
import {StatusStatType} from "@/types/Shikimori/StatusStatType";

export type AnimeType = {
    id: string;
    malId: string;
    name: string;
    russian: string;
    english: string;
    japanese: string;
    synonyms: string[];
    kind: string;
    rating: string;
    score: number;
    status: StatusType;
    episodes: number;
    episodesAired: number;
    description: string;
    duration: number;
    airedOn: IncompleteDateType;
    releasedOn: IncompleteDateType;
    url: string;
    season: string;
    poster: PosterType;
    fansubbers: string[];
    fandubbers: string[];
    licensors: string[];
    createdAt: string;
    updatedAt: string;
    nextEpisodeAt: string | null;
    isCensored: false;
    genres: GenreType[];
    studios: StudioType[];
    externalLinks: ExternalLinkType[];
    personRoles: PersonRoleType[];
    characterRoles: CharacterRoleType[];
    related: RelatedType[];
    videos: VideoType[];
    screenshots: ScreenshotType[];
    scoresStats: ScoreStatType[];
    statusesStats: StatusStatType[];
}